// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManager.Data;

#nullable disable

namespace TaskManager.Migrations
{
    [DbContext(typeof(TaskManagerDbContext))]
    [Migration("20260115202351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Finalize and submit the project documentation by end of the week.",
                            DueDate = new DateTime(2026, 1, 16, 20, 23, 50, 597, DateTimeKind.Utc).AddTicks(2515),
                            Status = "To Do",
                            Title = "Complete project documentation"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set up JWT authentication for the API.",
                            DueDate = new DateTime(2026, 2, 14, 20, 23, 50, 597, DateTimeKind.Utc).AddTicks(2524),
                            Status = "Done",
                            Title = "Implement user authentication"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create the initial database schema using EF Core.",
                            DueDate = new DateTime(2026, 1, 29, 20, 23, 50, 597, DateTimeKind.Utc).AddTicks(2526),
                            Status = "In Progress",
                            Title = "Design database schema"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure GitHub Actions for automated testing and deployment.",
                            DueDate = new DateTime(2026, 1, 20, 20, 23, 50, 597, DateTimeKind.Utc).AddTicks(2527),
                            Status = "Suspended",
                            Title = "Set up CI/CD pipeline"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implement unit tests for the service layer.",
                            DueDate = new DateTime(2026, 1, 22, 20, 23, 50, 597, DateTimeKind.Utc).AddTicks(2529),
                            Status = "To Do",
                            Title = "Write unit tests"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generate API documentation using Swagger.",
                            DueDate = new DateTime(2026, 2, 14, 20, 23, 50, 597, DateTimeKind.Utc).AddTicks(2531),
                            Status = "Done",
                            Title = "Create API documentation"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deploy the application to the production environment.",
                            DueDate = new DateTime(2026, 2, 8, 20, 23, 50, 597, DateTimeKind.Utc).AddTicks(2532),
                            Status = "Pending",
                            Title = "Deploy to production"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
